### ISSUE TITLE
USER STORY: Sign up information

### ISSUE THREAD

**Issue by MarkD117** [MarkD117/Agile-Project#3]
As a **user**, I can **get more information why to sign up**, so that **I can assess whether it would be beneficial for me to sign up to the website**.

### Acceptance Criteria:

- There should be an option to get more information
- Option should be on relevant sign up page
- User should be given a clear and detailed description
- User shoud be allowed to hide the information if neccesary\

### Tasks

- [ ]  Design more info button
- [ ]  Create message for sign up info
- [ ]  Design the HTML and CSS for the button and info
- [ ]  Create the code for showing and hiding the info
- [ ]  Test the completed functionality
